[package]
name = "umbral"
version = "0.1.0"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
edition = "2018"

[dependencies]
blake2 = "0.9"

[dependencies.rand_core]
version = "0.5"
features = ["getrandom"]

[dependencies.k256]
features = ["arithmetic", "rand"]
path = "/Users/bogdan/wb/github/elliptic-curves/k256"

